---
name: QA

on:
  push:

  workflow_dispatch:

jobs:
  units:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: ./restore-modules-cache-action
        with:
          working_directory: ./app

      - name: Testing
        run: |
          yarn test
        working-directory: ./app
        timeout-minutes: 5
